package com.example.util

import android.content.Context
import androidx.compose.runtime.compositionLocalOf
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

enum class AppLanguage(
    val englishName: String,
    val nativeName: String,
    val flagEmoji: String
) {
    EN("English", "English", "🇺🇸"),
    ES("Spanish", "Español", "🇪🇸"),
    FR("French", "Français", "🇫🇷"),
    DE("German", "Deutsch", "🇩🇪"),
    PT("Portuguese", "Português", "🇧🇷"),
    IT("Italian", "Italiano", "🇮🇹"),
    RU("Russian", "Русский", "🇷🇺"),
    JA("Japanese", "日本語", "🇯🇵"),
    KO("Korean", "한국어", "🇰🇷"),
    ZH("Chinese", "简体中文", "🇨🇳"),
    HI("Hindi", "हिन्दी", "🇮🇳"),
    AR("Arabic", "العربية", "🇸🇦");

    val displayName: String get() = "$flagEmoji $nativeName"
}

data class AppStrings(
    // Bottom Navigation
    val navHome: String = "Home",
    val navSubscriptions: String = "Subscriptions",
    val navLibrary: String = "Library",
    val navShorts: String = "Shorts",
    val navSearch: String = "Search",

    // Library Tabs
    val tabSubjects: String = "Subjects",
    val tabDownloads: String = "Downloads",
    val tabFavorites: String = "Favorites",
    val tabWatchLater: String = "Watch Later",
    val tabHistory: String = "History",

    // Library Content
    val libraryTitle: String = "Library & Downloads",
    val customPlaylists: String = "Custom Playlists",
    val addCategory: String = "Add Category",
    val noFavoritesText: String = "No favorite videos saved yet. Tap the star icon on any video to bookmark it here!",
    val noWatchLaterText: String = "Your Watch Later queue is empty. Add videos from the home feed to save them for later!",
    val noHistoryText: String = "No watch history recorded yet. Videos you watch will automatically appear here!",
    val noDownloadsText: String = "No downloaded videos yet. Tap the download icon while playing any video for offline viewing.",

    // Top Category Filters
    val catAll: String = "All",
    val catLast24h: String = "⏰ Last 24h",
    val catTechCode: String = "Tech & Code",
    val catMusic: String = "Music",
    val catTutorials: String = "Tutorials",
    val catGaming: String = "Gaming",
    val catFocusAmbient: String = "Focus & Ambient",

    // Video Player Actions
    val btnAiSummary: String = "AI Summary",
    val btnDownload: String = "Download",
    val btnDownloaded: String = "Downloaded",
    val btnShare: String = "Share",
    val btnLike: String = "Like",
    val btnLiked: String = "Liked",
    val btnDislike: String = "Dislike",
    val btnDisliked: String = "Disliked",
    val sponsorSkipped: String = "Skipped Sponsor",

    // Settings
    val settingsTitle: String = "Settings & Algorithm",
    val appLanguageTitle: String = "App Language",
    val appLanguageSub: String = "Select your preferred display language for instant UI update",
    val adBlockActive: String = "AdBlock Active",
    val adBlockSub: String = "Commercial YouTube ads suppressed during playback.",
    val advertsAllowed: String = "Adverts Allowed",
    val advertsAllowedSub: String = "Standard YouTube ads play.",
    val closeBtn: String = "Close",

    // Try Our Other Products
    val tryOurOtherProducts: String = "Try Our Other Products ✨",
    val otherProductsSub: String = "Discover more powerful tools created by our team:",
    val visitWebsite: String = "Visit Website 🌐",
    val getOnStore: String = "Get on Store 🛒"
)

object LanguageManager {
    private const val PREFS_NAME = "vixz_language_prefs"
    private const val KEY_LANGUAGE = "selected_app_language"

    private val _currentLanguage = MutableStateFlow(AppLanguage.EN)
    val currentLanguage: StateFlow<AppLanguage> = _currentLanguage.asStateFlow()

    private val translations = mapOf(
        AppLanguage.EN to AppStrings(),
        AppLanguage.ES to AppStrings(
            navHome = "Inicio",
            navSubscriptions = "Suscripciones",
            navLibrary = "Biblioteca",
            navShorts = "Shorts",
            navSearch = "Buscar",
            tabSubjects = "Temas",
            tabDownloads = "Descargas",
            tabFavorites = "Favoritos",
            tabWatchLater = "Ver Más Tarde",
            tabHistory = "Historial",
            libraryTitle = "Biblioteca y Descargas",
            customPlaylists = "Listas Personalizadas",
            addCategory = "Añadir Categoría",
            noFavoritesText = "Aún no hay videos favoritos. ¡Toca la estrella en cualquier video para guardarlo aquí!",
            noWatchLaterText = "Tu lista de Ver Más Tarde está vacía. ¡Añade videos desde el inicio para verlos luego!",
            noHistoryText = "Aún no hay historial de reproducción. ¡Los videos que veas aparecerán aquí!",
            noDownloadsText = "No hay videos descargados. Toca el botón de descarga en el reproductor para ver sin conexión.",
            catAll = "Todos",
            catLast24h = "⏰ Últimas 24h",
            catTechCode = "Tecnología y Código",
            catMusic = "Música",
            catTutorials = "Tutoriales",
            catGaming = "Videojuegos",
            catFocusAmbient = "Enfoque y Ambiente",
            btnAiSummary = "Resumen IA",
            btnDownload = "Descargar",
            btnDownloaded = "Descargado",
            btnShare = "Compartir",
            btnLike = "Me gusta",
            btnLiked = "Te gustó",
            btnDislike = "No me gusta",
            btnDisliked = "Ocultado",
            sponsorSkipped = "Patrocinio Omitido",
            settingsTitle = "Ajustes y Algoritmo",
            appLanguageTitle = "Idioma de la Aplicación",
            appLanguageSub = "Selecciona tu idioma preferido para actualización instantánea",
            adBlockActive = "AdBlock Activo",
            adBlockSub = "Anuncios comerciales de YouTube bloqueados.",
            advertsAllowed = "Anuncios Permitidos",
            advertsAllowedSub = "Se reproducen anuncios normales.",
            closeBtn = "Cerrar",
            tryOurOtherProducts = "Prueba Nuestros Otros Productos ✨",
            otherProductsSub = "Descubre más herramientas desarrolladas por nuestro equipo:",
            visitWebsite = "Visitar Sitio Web 🌐",
            getOnStore = "Obtener en Tienda 🛒"
        ),
        AppLanguage.FR to AppStrings(
            navHome = "Accueil",
            navSubscriptions = "Abonnements",
            navLibrary = "Bibliothèque",
            navShorts = "Shorts",
            navSearch = "Rechercher",
            tabSubjects = "Sujets",
            tabDownloads = "Téléchargements",
            tabFavorites = "Favoris",
            tabWatchLater = "À regarder plus tard",
            tabHistory = "Historique",
            libraryTitle = "Bibliothèque et Téléchargements",
            customPlaylists = "Playlists Personnalisées",
            addCategory = "Ajouter Catégorie",
            noFavoritesText = "Aucune vidéo favorite. Touchez l'étoile sur une vidéo pour l'ajouter ici!",
            noWatchLaterText = "Votre liste À regarder plus tard est vide.",
            noHistoryText = "Aucun historique pour le moment. Les vidéos visionnées apparaîtront ici.",
            noDownloadsText = "Aucun téléchargement. Téléchargez des vidéos pour les regarder hors ligne.",
            catAll = "Tout",
            catLast24h = "⏰ Dernières 24h",
            catTechCode = "Tech et Code",
            catMusic = "Musique",
            catTutorials = "Tutoriels",
            catGaming = "Jeux Vidéo",
            catFocusAmbient = "Focus et Ambiance",
            btnAiSummary = "Résumé IA",
            btnDownload = "Télécharger",
            btnDownloaded = "Téléchargé",
            btnShare = "Partager",
            btnLike = "J'aime",
            btnLiked = "Aimé",
            btnDislike = "Je n'aime pas",
            btnDisliked = "Masqué",
            sponsorSkipped = "Sponsor Ignoré",
            settingsTitle = "Paramètres et Algorithme",
            appLanguageTitle = "Langue de l'Application",
            appLanguageSub = "Choisissez votre langue pour une mise à jour instantanée de l'interface",
            adBlockActive = "AdBlock Actif",
            adBlockSub = "Publicités commerciales YouTube bloquées.",
            advertsAllowed = "Publicités Autorisées",
            advertsAllowedSub = "Les publicités normales sont lues.",
            closeBtn = "Fermer",
            tryOurOtherProducts = "Essayez Nos Autres Produits ✨",
            otherProductsSub = "Découvrez d'autres outils créés par notre équipe :",
            visitWebsite = "Visiter le Site 🌐",
            getOnStore = "Voir sur le Store 🛒"
        ),
        AppLanguage.DE to AppStrings(
            navHome = "Startseite",
            navSubscriptions = "Abos",
            navLibrary = "Mediathek",
            navShorts = "Shorts",
            navSearch = "Suchen",
            tabSubjects = "Themen",
            tabDownloads = "Downloads",
            tabFavorites = "Favoriten",
            tabWatchLater = "Später ansehen",
            tabHistory = "Verlauf",
            libraryTitle = "Mediathek & Downloads",
            customPlaylists = "Eigene Playlists",
            addCategory = "Kategorie hinzufügen",
            noFavoritesText = "Noch keine Favoriten gespeichert. Tippe auf den Stern bei einem Video!",
            noWatchLaterText = "Deine 'Später ansehen'-Liste ist leer.",
            noHistoryText = "Noch kein Verlauf vorhanden. Angesehene Videos erscheinen hier.",
            noDownloadsText = "Keine Downloads vorhanden. Lade Videos für die Offline-Wiedergabe herunter.",
            catAll = "Alle",
            catLast24h = "⏰ Letzte 24 Std.",
            catTechCode = "Tech & Programmierung",
            catMusic = "Musik",
            catTutorials = "Tutorials",
            catGaming = "Gaming",
            catFocusAmbient = "Fokus & Ambient",
            btnAiSummary = "KI-Zusammenfassung",
            btnDownload = "Herunterladen",
            btnDownloaded = "Heruntergeladen",
            btnShare = "Teilen",
            btnLike = "Gefällt mir",
            btnLiked = "Gefällt mir",
            btnDislike = "Gefällt mir nicht",
            btnDisliked = "Ausgeblendet",
            sponsorSkipped = "Sponsor übersprungen",
            settingsTitle = "Einstellungen & Algorithmus",
            appLanguageTitle = "App-Sprache",
            appLanguageSub = "Wähle deine bevorzugte Anzeigesprache",
            adBlockActive = "AdBlock Aktiv",
            adBlockSub = "Kommerzielle YouTube-Werbung wird blockiert.",
            advertsAllowed = "Werbung Erlaubt",
            advertsAllowedSub = "Standardmäßige Werbung wird abgespielt.",
            closeBtn = "Schließen",
            tryOurOtherProducts = "Entdecke Unsere Weiteren Produkte ✨",
            otherProductsSub = "Erfahre mehr über unsere weiteren Tools:",
            visitWebsite = "Website besuchen 🌐",
            getOnStore = "Im Store ansehen 🛒"
        ),
        AppLanguage.PT to AppStrings(
            navHome = "Início",
            navSubscriptions = "Inscrições",
            navLibrary = "Biblioteca",
            navShorts = "Shorts",
            navSearch = "Pesquisar",
            tabSubjects = "Assuntos",
            tabDownloads = "Downloads",
            tabFavorites = "Favoritos",
            tabWatchLater = "Assistir Mais Tarde",
            tabHistory = "Histórico",
            libraryTitle = "Biblioteca e Downloads",
            customPlaylists = "Playlists Personalizadas",
            addCategory = "Adicionar Categoria",
            noFavoritesText = "Nenhum vídeo favorito salvo ainda.",
            noWatchLaterText = "Sua fila de Assistir Mais Tarde está vazia.",
            noHistoryText = "Nenhum histórico registrado ainda.",
            noDownloadsText = "Nenhum vídeo baixado ainda.",
            catAll = "Todos",
            catLast24h = "⏰ Últimas 24h",
            catTechCode = "Tecnologia e Código",
            catMusic = "Música",
            catTutorials = "Tutoriais",
            catGaming = "Jogos",
            catFocusAmbient = "Foco e Ambiente",
            btnAiSummary = "Resumo IA",
            btnDownload = "Baixar",
            btnDownloaded = "Baixado",
            btnShare = "Compartilhar",
            btnLike = "Gostei",
            btnLiked = "Gostei",
            btnDislike = "Não Gostei",
            btnDisliked = "Oculto",
            sponsorSkipped = "Patrocínio Ignorado",
            settingsTitle = "Configurações e Algoritmo",
            appLanguageTitle = "Idioma do Aplicativo",
            appLanguageSub = "Selecione seu idioma para atualização instantânea",
            adBlockActive = "AdBlock Ativo",
            adBlockSub = "Anúncios comerciais do YouTube bloqueados.",
            advertsAllowed = "Anúncios Permitidos",
            advertsAllowedSub = "Anúncios normais são reproduzidos.",
            closeBtn = "Fechar",
            tryOurOtherProducts = "Experimente Nossos Outros Produtos ✨",
            otherProductsSub = "Conheça mais ferramentas criadas por nossa equipe:",
            visitWebsite = "Visitar Site 🌐",
            getOnStore = "Obter na Loja 🛒"
        ),
        AppLanguage.IT to AppStrings(
            navHome = "Home",
            navSubscriptions = "Iscrizioni",
            navLibrary = "Raccolta",
            navShorts = "Shorts",
            navSearch = "Cerca",
            tabSubjects = "Argomenti",
            tabDownloads = "Download",
            tabFavorites = "Preferiti",
            tabWatchLater = "Guarda Più Tardi",
            tabHistory = "Cronologia",
            libraryTitle = "Raccolta e Download",
            customPlaylists = "Playlist Personalizzate",
            addCategory = "Aggiungi Categoria",
            catAll = "Tutti",
            catLast24h = "⏰ Ultime 24h",
            catTechCode = "Tech e Codice",
            catMusic = "Musica",
            catTutorials = "Tutorial",
            catGaming = "Gaming",
            catFocusAmbient = "Focus e Ambient",
            btnAiSummary = "Riassunto IA",
            btnDownload = "Scarica",
            btnDownloaded = "Scaricato",
            btnShare = "Condividi",
            btnLike = "Mi piace",
            btnLiked = "Piaciuto",
            btnDislike = "Non mi piace",
            btnDisliked = "Nascosto",
            sponsorSkipped = "Sponsor Saltato",
            settingsTitle = "Impostazioni e Algoritmo",
            appLanguageTitle = "Lingua dell'Applicazione",
            appLanguageSub = "Seleziona la tua lingua preferita",
            adBlockActive = "AdBlock Attivo",
            adBlockSub = "Annunci YouTube commerciali bloccati.",
            closeBtn = "Chiudi",
            tryOurOtherProducts = "Prova i Nostri Altri Prodotti ✨",
            otherProductsSub = "Scopri altri strumenti creati dal nostro team:",
            visitWebsite = "Visita il Sito 🌐",
            getOnStore = "Apri nello Store 🛒"
        ),
        AppLanguage.RU to AppStrings(
            navHome = "Главная",
            navSubscriptions = "Подписки",
            navLibrary = "Библиотека",
            navShorts = "Shorts",
            navSearch = "Поиск",
            tabSubjects = "Темы",
            tabDownloads = "Загрузки",
            tabFavorites = "Избранное",
            tabWatchLater = "Смотреть позже",
            tabHistory = "История",
            libraryTitle = "Библиотека и Загрузки",
            customPlaylists = "Свои плейлисты",
            addCategory = "Добавить категорию",
            catAll = "Все",
            catLast24h = "⏰ Последние 24ч",
            catTechCode = "Технологии и Код",
            catMusic = "Музыка",
            catTutorials = "Обучение",
            catGaming = "Игры",
            catFocusAmbient = "Фокус и Эмбиент",
            btnAiSummary = "ИИ Итоги",
            btnDownload = "Скачать",
            btnDownloaded = "Скачано",
            btnShare = "Поделиться",
            btnLike = "Нравится",
            btnLiked = "Вам нравится",
            btnDislike = "Не нравится",
            btnDisliked = "Скрыто",
            sponsorSkipped = "Спонсор пропущен",
            settingsTitle = "Настройки и Алгоритм",
            appLanguageTitle = "Язык приложения",
            appLanguageSub = "Выберите язык для мгновенного обновления интерфейса",
            adBlockActive = "AdBlock Включен",
            adBlockSub = "Реклама YouTube заблокирована.",
            closeBtn = "Закрыть",
            tryOurOtherProducts = "Попробуйте другие наши продукты ✨",
            otherProductsSub = "Узнайте о других инструментах нашей команды:",
            visitWebsite = "Перейти на сайт 🌐",
            getOnStore = "Открыть в Store 🛒"
        ),
        AppLanguage.JA to AppStrings(
            navHome = "ホーム",
            navSubscriptions = "登録チャンネル",
            navLibrary = "ライブラリ",
            navShorts = "Shorts",
            navSearch = "検索",
            tabSubjects = "カテゴリー",
            tabDownloads = "ダウンロード",
            tabFavorites = "お気に入り",
            tabWatchLater = "後で見る",
            tabHistory = "再生履歴",
            libraryTitle = "ライブラリ＆保存",
            customPlaylists = "カスタムプレイリスト",
            addCategory = "カテゴリー追加",
            catAll = "すべて",
            catLast24h = "⏰ 24時間以内",
            catTechCode = "テクノロジー＆開発",
            catMusic = "音楽",
            catTutorials = "チュートリアル",
            catGaming = "ゲーム",
            catFocusAmbient = "集中・環境音",
            btnAiSummary = "AI 要約",
            btnDownload = "ダウンロード",
            btnDownloaded = "保存済み",
            btnShare = "共有",
            btnLike = "高評価",
            btnLiked = "高評価済み",
            btnDislike = "低評価",
            btnDisliked = "非表示",
            sponsorSkipped = "スポンサー自動スキップ",
            settingsTitle = "設定＆おすすめ調整",
            appLanguageTitle = "アプリの言語",
            appLanguageSub = "表示言語を選択すると即座にUIが更新されます",
            adBlockActive = "広告ブロック有効",
            adBlockSub = "YouTube広告は再生されません。",
            closeBtn = "閉じる",
            tryOurOtherProducts = "他の製品も試してみる ✨",
            otherProductsSub = "チームが開発した便利なツールをチェック：",
            visitWebsite = "公式サイトを見る 🌐",
            getOnStore = "ストアで入手 🛒"
        ),
        AppLanguage.KO to AppStrings(
            navHome = "홈",
            navSubscriptions = "구독",
            navLibrary = "보관함",
            navShorts = "Shorts",
            navSearch = "검색",
            tabSubjects = "주제",
            tabDownloads = "오프라인 저장",
            tabFavorites = "좋아요 표시한 동영상",
            tabWatchLater = "나중에 볼 동영상",
            tabHistory = "시청 기록",
            libraryTitle = "보관함 및 저장목록",
            customPlaylists = "맞춤 재생목록",
            addCategory = "카테고리 추가",
            catAll = "전체",
            catLast24h = "⏰ 최근 24시간",
            catTechCode = "기술 및 코딩",
            catMusic = "음악",
            catTutorials = "튜토리얼",
            catGaming = "게임",
            catFocusAmbient = "집중 및 배경음악",
            btnAiSummary = "AI 요약",
            btnDownload = "다운로드",
            btnDownloaded = "저장됨",
            btnShare = "공유",
            btnLike = "좋아요",
            btnLiked = "좋아요 완료",
            btnDislike = "싫어요",
            btnDisliked = "숨김 처리됨",
            sponsorSkipped = "스폰서 건너뜀",
            settingsTitle = "설정 및 알고리즘",
            appLanguageTitle = "앱 언어",
            appLanguageSub = "원하는 언어를 선택하면 즉시 적용됩니다",
            adBlockActive = "광고 차단 활성",
            adBlockSub = "YouTube 광고 없이 재생됩니다.",
            closeBtn = "닫기",
            tryOurOtherProducts = "다른 추천 앱 사용해보기 ✨",
            otherProductsSub = "저희 팀이 개발한 강력한 도구를 확인해보세요:",
            visitWebsite = "웹사이트 방문 🌐",
            getOnStore = "스토어에서 받기 🛒"
        ),
        AppLanguage.ZH to AppStrings(
            navHome = "首页",
            navSubscriptions = "订阅",
            navLibrary = "媒体库",
            navShorts = "短视频",
            navSearch = "搜索",
            tabSubjects = "主题分类",
            tabDownloads = "离线下载",
            tabFavorites = "收藏夹",
            tabWatchLater = "稍后观看",
            tabHistory = "播放历史",
            libraryTitle = "媒体库与下载",
            customPlaylists = "自定义播放列表",
            addCategory = "添加分类",
            catAll = "全部",
            catLast24h = "⏰ 最近24小时",
            catTechCode = "科技与编程",
            catMusic = "音乐",
            catTutorials = "教学指南",
            catGaming = "游戏",
            catFocusAmbient = "专注与白噪音",
            btnAiSummary = "AI 摘要",
            btnDownload = "下载",
            btnDownloaded = "已下载",
            btnShare = "分享",
            btnLike = "点赞",
            btnLiked = "已点赞",
            btnDislike = "不喜欢",
            btnDisliked = "已隐藏",
            sponsorSkipped = "已跳过赞助片段",
            settingsTitle = "设置与算法",
            appLanguageTitle = "应用语言",
            appLanguageSub = "选择界面语言，0毫秒即时生效",
            adBlockActive = "广告拦截已开启",
            adBlockSub = "YouTube商业广告已被屏蔽。",
            closeBtn = "关闭",
            tryOurOtherProducts = "体验我们的其他产品 ✨",
            otherProductsSub = "探索由我们团队打造的更多强大工具：",
            visitWebsite = "访问官方网站 🌐",
            getOnStore = "前往应用商店 🛒"
        ),
        AppLanguage.HI to AppStrings(
            navHome = "होम",
            navSubscriptions = "सब्सक्रिप्शन",
            navLibrary = "लाइब्रेरी",
            navShorts = "Shorts",
            navSearch = "खोजें",
            tabSubjects = "विषय",
            tabDownloads = "डाउनलोड",
            tabFavorites = "पसंदीदा",
            tabWatchLater = "बाद में देखें",
            tabHistory = "इतिहास",
            libraryTitle = "लाइब्रेरी और डाउनलोड",
            customPlaylists = "कस्टम प्लेलिस्ट",
            addCategory = "श्रेणी जोड़ें",
            catAll = "सभी",
            catLast24h = "⏰ पिछले 24 घंटे",
            catTechCode = "तकनीक और कोड",
            catMusic = "संगीत",
            catTutorials = "ट्यूटोरियल",
            catGaming = "गेमिंग",
            catFocusAmbient = "फोकस संगीत",
            btnAiSummary = "AI सारांश",
            btnDownload = "डाउनलोड",
            btnDownloaded = "डाउनलोड हो गया",
            btnShare = "शेयर करें",
            btnLike = "पसंद",
            btnLiked = "पसंद किया",
            btnDislike = "नापसंद",
            btnDisliked = "छिपाया गया",
            sponsorSkipped = "प्रायोजक छोड़ा गया",
            settingsTitle = "सेटिंग्स और एल्गोरिदम",
            appLanguageTitle = "ऐप की भाषा",
            appLanguageSub = "तत्काल अपडेट के लिए अपनी पसंदीदा भाषा चुनें",
            adBlockActive = "विज्ञापन ब्लॉक सक्रिय",
            adBlockSub = "YouTube विज्ञापन अवरुद्ध हैं।",
            closeBtn = "बंद करें",
            tryOurOtherProducts = "हमारे अन्य उत्पाद आज़माएं ✨",
            otherProductsSub = "हमारी टीम द्वारा बनाए गए अन्य उपयोगी ऐप्स:",
            visitWebsite = "वेबसाइट देखें 🌐",
            getOnStore = "स्टोर से प्राप्त करें 🛒"
        ),
        AppLanguage.AR to AppStrings(
            navHome = "الرئيسية",
            navSubscriptions = "الاشتراكات",
            navLibrary = "المكتبة",
            navShorts = "Shorts",
            navSearch = "بحث",
            tabSubjects = "المواضيع",
            tabDownloads = "التنزيلات",
            tabFavorites = "المفضلة",
            tabWatchLater = "المشاهدة لاحقاً",
            tabHistory = "سجل المشاهدة",
            libraryTitle = "المكتبة والتنزيلات",
            customPlaylists = "قوائم التشغيل",
            addCategory = "إضافة فئة",
            catAll = "الكل",
            catLast24h = "⏰ آخر 24 ساعة",
            catTechCode = "التقنية والبرمجة",
            catMusic = "موسيقى",
            catTutorials = "شروحات",
            catGaming = "ألعاب",
            catFocusAmbient = "تركيز واسترخاء",
            btnAiSummary = "ملخص AI",
            btnDownload = "تنزيل",
            btnDownloaded = "تم التنزيل",
            btnShare = "مشاركة",
            btnLike = "أعجبني",
            btnLiked = "تم الإعجاب",
            btnDislike = "لم يعجبني",
            btnDisliked = "مخفي",
            sponsorSkipped = "تم تخطي الإعلان",
            settingsTitle = "الإعدادات والخوارزمية",
            appLanguageTitle = "لغة التطبيق",
            appLanguageSub = "اختر لغتك المفضلة لتحديث الواجهة فوراً",
            adBlockActive = "مانع الإعلانات مفعّل",
            adBlockSub = "تم حظر إعلانات يوتيوب التجارية.",
            closeBtn = "إغلاق",
            tryOurOtherProducts = "جرب منتجاتنا الأخرى ✨",
            otherProductsSub = "اكتشف المزيد من الأدوات المطورة بواسطة فريقنا:",
            visitWebsite = "زيارة الموقع 🌐",
            getOnStore = "الحصول عليه من المتجر 🛒"
        )
    )

    fun init(context: Context) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val savedLangName = prefs.getString(KEY_LANGUAGE, AppLanguage.EN.name) ?: AppLanguage.EN.name
        val lang = try {
            AppLanguage.valueOf(savedLangName)
        } catch (e: Exception) {
            AppLanguage.EN
        }
        _currentLanguage.value = lang
    }

    fun setLanguage(context: Context, language: AppLanguage) {
        _currentLanguage.value = language
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putString(KEY_LANGUAGE, language.name).apply()
    }

    fun getStrings(language: AppLanguage = _currentLanguage.value): AppStrings {
        return translations[language] ?: translations[AppLanguage.EN] ?: AppStrings()
    }
}

val LocalAppStrings = compositionLocalOf { AppStrings() }
